[package]
name = "femto_common"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = "0.20.1"
handlebars = { version = "6.3.2", features = ["string_helpers"] }
reqwest = "0.12.15"
serde = { version = "1.0.219", features = ["derive"] }
